(function(){
'use strict';
var OWNER='amitabhkumar051222/drivespeclab-data@main',BASE='https://cdn.jsdelivr.net/gh/'+OWNER+'/',overlay=null,db=null,brand='',observer=null;
var SLUG={'Mercedes-Benz':'mercedes-benz','Land Rover':'land-rover','Tata Motors':'tata-motors','Volkswagen':'volkswagen'};
function q(s,r){return(r||document).querySelector(s)}function qa(s,r){return[].slice.call((r||document).querySelectorAll(s))}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function slug(x){return SLUG[x]||String(x||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function brandFromPath(){var m=location.pathname.match(/\/search\/label\/([^/?#]+)/i);if(!m)return'';var x='';try{x=decodeURIComponent(m[1]).replace(/\+/g,' ')}catch(e){x=m[1]}var A={'Land-Rover':'Land Rover','Tata':'Tata Motors','Tata-Motors':'Tata Motors','Mercedes-Benz':'Mercedes-Benz'};return A[x]||x.replace(/-/g,' ')}
function modelFromHash(){if((location.hash||'').indexOf('#usmodel=')!==0)return'';try{return decodeURIComponent(location.hash.slice(9))}catch(e){return location.hash.slice(9)}}
function loadJson(u){return fetch(u,{cache:'no-cache'}).then(function(r){return r.ok?r.json():null}).catch(function(){return null})}
function mergeOverlay(){if(!db||!overlay||!overlay.models||!db.sidecar)return;db.sidecar.models=db.sidecar.models||{};Object.keys(overlay.models).forEach(function(n){var old=db.sidecar.models[n]||{},enh=overlay.models[n]||{},z={};Object.keys(old).forEach(function(k){z[k]=old[k]});Object.keys(enh).forEach(function(k){z[k]=enh[k]});db.sidecar.models[n]=z});db.sidecar.v6_verified_on=overlay.verified_on||null}
function val(o,keys,unit){for(var i=0;i<keys.length;i++){var v=o&&o[keys[i]];if(v!==undefined&&v!==null&&v!==''){if(typeof v==='number')return v.toLocaleString('en-US')+(unit?' '+unit:'');return String(v)}}return''}
function rows(a){var z='';a.forEach(function(x){if(x[1])z+='<tr><th>'+esc(x[0])+'</th><td>'+esc(x[1])+'</td></tr>'});return z}
function findSec(root,title){var out=null;qa('.sec',root).some(function(s){var h=q('h3',s);if(h&&h.textContent.trim()===title){out=s;return true}return false});return out}
function replaceSec(root,title,data,newTitle){var sec=findSec(root,title),r=rows(data);if(!sec)return;if(!r){sec.style.display='none';return}sec.style.display='';sec.innerHTML='<h3>'+esc(newTitle||title)+'</h3><table class="tbl">'+r+'</table>'}
function cleanGeneric(root){var bad=['varies by trim','varies by configuration','varies by powertrain','verify official manufacturer specification','where applicable','charging capability varies','see official manufacturer specification'];qa('.sec .tbl tr',root).forEach(function(tr){var t=tr.textContent.toLowerCase();if(bad.some(function(x){return t.indexOf(x)>-1}))tr.remove()});qa('.sec',root).forEach(function(sec){var h=q('h3',sec);if(h&&/official verified performance/i.test(h.textContent))sec.style.display='none';var table=q('.tbl',sec);if(table&&!q('tr',table))sec.style.display='none'})}
function enhanceToyota(root,name){if(!overlay||!overlay.models||!overlay.models[name])return;var o=overlay.models[name];replaceSec(root,'Engine, motor & performance',[
['Engine / motor',val(o,['engine','motor'])],['Power output',val(o,['horsepower'],'hp')],['Torque',val(o,['torque_lb_ft','torque'],'lb-ft')],['Transmission',val(o,['transmission'])],['Drivetrain detail',val(o,['drivetrain_detail'])],['0–60 mph',val(o,['zero_to_60','zero_to_60_sec'],typeof o.zero_to_60_sec==='number'?'sec':'')]
]);replaceSec(root,'Efficiency, range & charging',[
['EPA efficiency',val(o,['mpg_city_highway_combined','mpg_city_highway','mpg_combined','mpg_combined_up_to'],typeof o.mpg_combined==='number'||typeof o.mpg_combined_up_to==='number'?'MPG':'')],['MPGe',val(o,['mpge_city_highway_combined','mpge_combined'],typeof o.mpge_combined==='number'?'MPGe':'')],['EPA / driving range',val(o,['range_miles','range_miles_up_to','epa_range_miles','phev_electric_range_miles'],typeof o.range_miles==='number'||typeof o.range_miles_up_to==='number'?'miles':'')],['Battery',val(o,['battery_kwh','battery'],typeof o.battery_kwh==='number'?'kWh':'')],['Charging',val(o,['charging'])],['Fueling',val(o,['fueling'])]
],'Efficiency, range & energy');replaceSec(root,'Dimensions, cargo & capability',[
['Dimensions',val(o,['dimensions'])],['Cargo capacity',val(o,['cargo_cu_ft','cargo_cu_ft_up_to'],typeof o.cargo_cu_ft==='number'||typeof o.cargo_cu_ft_up_to==='number'?'cu ft':'')],['Ground clearance',val(o,['ground_clearance_in','ground_clearance_in_up_to'],typeof o.ground_clearance_in==='number'||typeof o.ground_clearance_in_up_to==='number'?'in':'')],['Towing',val(o,['towing_lbs_up_to','towing_lbs'],typeof o.towing_lbs_up_to==='number'||typeof o.towing_lbs==='number'?'lb':'')],['Payload',val(o,['payload_lbs_up_to','payload_lbs'],typeof o.payload_lbs_up_to==='number'||typeof o.payload_lbs==='number'?'lb':'')],['Bed lengths',val(o,['bed_lengths'])]
]);replaceSec(root,'Technology & safety',[["Technology",val(o,['technology','tech'])],["Safety / ADAS",val(o,['safety'])]]);var w=findSec(root,'Warranty');if(w&&(o.ev_battery_warranty||o.fuel_cell_warranty)){var table=q('.tbl',w);if(table){if(o.ev_battery_warranty)table.insertAdjacentHTML('beforeend','<tr><th>EV battery warranty</th><td>'+esc(o.ev_battery_warranty)+'</td></tr>');if(o.fuel_cell_warranty)table.insertAdjacentHTML('beforeend','<tr><th>Fuel-cell warranty</th><td>'+esc(o.fuel_cell_warranty)+'</td></tr>')}}var copy=q('.copy',root);if(copy&&!q('.v6Badge',copy))copy.insertAdjacentHTML('afterbegin','<span class="v6Badge">✓ V6 verified specification layer</span>');if(o.image){var hero=q('.dhero img',root);if(hero)hero.src=o.image;var first=q('.dgal img',root);if(first)first.src=o.image}if(!q('.v6Policy',root)){var last=qa('.sec',root).filter(function(s){return s.style.display!=='none'}).pop();if(last)last.insertAdjacentHTML('afterend','<section class="sec v6Policy"><h3>DriveSpecLab verification policy</h3><p>Only verified published values are shown here. Missing specifications are omitted rather than replaced with estimates. Trim, wheel, drivetrain and option choices can change manufacturer figures.</p></section>')}}
function imageList(root){return qa('.dhero img,.dgal img',root).filter(function(x){return x.style.display!=='none'&&x.src})}
function lightbox(){var b=q('#dslV6Lightbox');if(b)return b;b=document.createElement('div');b.id='dslV6Lightbox';b.innerHTML='<button class="v6Close" type="button">×</button><button class="v6Prev" type="button">‹</button><figure><img alt=""/><figcaption></figcaption></figure><button class="v6Next" type="button">›</button><span class="v6Count"></span>';document.body.appendChild(b);return b}
var lbIndex=0,lbRoot=null,touchX=null;function showLb(root,index){var a=imageList(root),b=lightbox();if(!a.length)return;lbRoot=root;lbIndex=(index+a.length)%a.length;var im=q('figure img',b),src=a[lbIndex].src,alt=a[lbIndex].alt||'';im.src=src;im.alt=alt;q('figcaption',b).textContent=alt;q('.v6Count',b).textContent=(lbIndex+1)+' / '+a.length;b.classList.add('on');document.documentElement.classList.add('v6NoScroll')}function closeLb(){var b=q('#dslV6Lightbox');if(b)b.classList.remove('on');document.documentElement.classList.remove('v6NoScroll')}
function bindRoot(root){if(root.dataset.v6bound)return;root.dataset.v6bound='1';qa('.dc',root).forEach(function(c){var d=q('.dm',c),btn=q('[data-open]',c);if(d&&btn){d.setAttribute('data-open',btn.getAttribute('data-open'));d.setAttribute('role','button');d.setAttribute('tabindex','0')}});root.addEventListener('click',function(e){var img=e.target.closest('.dhero img,.dgal img');if(img){e.preventDefault();e.stopPropagation();var a=imageList(root),i=a.indexOf(img);showLb(root,i<0?0:i)}});root.addEventListener('keydown',function(e){var d=e.target.closest('.dm[data-open]');if(d&&(e.key==='Enter'||e.key===' ')){e.preventDefault();var b=q('.btn',d.closest('.dc'));if(b)b.click()}})}
function process(){var root=q('#dslVehicleDB');if(!root)return;bindRoot(root);qa('.dc',root).forEach(function(c){var n=q('h2',c),im=q('.dm img',c);if(n&&im&&overlay&&overlay.models&&overlay.models[n.textContent.trim()]&&overlay.models[n.textContent.trim()].image)im.src=overlay.models[n.textContent.trim()].image});var detail=q('.detail.on',root);if(!detail)return;var mn=modelFromHash();if(detail.dataset.v6processed!==mn||!q('.v6RunMarker',detail)){cleanGeneric(detail);if(brand==='Toyota')enhanceToyota(detail,mn);detail.dataset.v6processed=mn;detail.insertAdjacentHTML('beforeend','<i class="v6RunMarker" hidden></i>')}qa('.dhero,.galleryItem,.dgal>div',detail).forEach(function(x){x.classList.add('v6Clickable')});qa('.dhero img,.dgal img',detail).forEach(function(x){x.setAttribute('title','Tap to enlarge image')})}
function watch(){if(observer)return;observer=new MutationObserver(function(){setTimeout(process,0)});observer.observe(document.documentElement,{childList:true,subtree:true});process()}
function css(){if(q('#dslV6Css'))return;var s=document.createElement('style');s.id='dslV6Css';s.textContent='.v6Badge{display:inline-flex;margin:0 0 9px;padding:5px 8px;border:1px solid #bce9cf;background:#e7f8ef;color:#087443;border-radius:999px;font-size:10px;font-weight:900}.v6Policy{background:#f8fbff!important}.v6Policy p{margin:0;color:#617084;font-size:12px;line-height:1.6}.dm[data-open]{cursor:pointer}.v6Clickable{cursor:zoom-in;position:relative}.v6Clickable:after{content:"Tap to enlarge";position:absolute;right:9px;bottom:9px;background:#071d3fdd;color:#fff;padding:5px 8px;border-radius:999px;font-size:9px;font-weight:900;pointer-events:none}#dslV6Lightbox{position:fixed;inset:0;z-index:2147483000;background:rgba(3,10,18,.95);display:none;align-items:center;justify-content:center;padding:52px 58px;color:#fff}#dslV6Lightbox.on{display:flex}#dslV6Lightbox figure{margin:0;max-width:min(1180px,92vw);max-height:88vh;display:flex;flex-direction:column;align-items:center;gap:10px}#dslV6Lightbox figure img{max-width:100%;max-height:78vh;object-fit:contain;background:#fff;border-radius:10px}#dslV6Lightbox figcaption{font-size:13px;color:#dce7ef;text-align:center}#dslV6Lightbox button{position:absolute;border:0;color:#fff;background:rgba(255,255,255,.13);cursor:pointer}.v6Close{right:18px;top:16px;width:44px;height:44px;border-radius:50%;font-size:30px}.v6Prev,.v6Next{top:50%;transform:translateY(-50%);width:50px;height:64px;border-radius:12px;font-size:44px}.v6Prev{left:12px}.v6Next{right:12px}.v6Count{position:absolute;left:50%;bottom:13px;transform:translateX(-50%);background:#0008;padding:6px 9px;border-radius:999px;font-size:11px}.v6NoScroll{overflow:hidden!important}@media(max-width:590px){#dslV6Lightbox{padding:58px 10px 54px}.v6Prev,.v6Next{top:auto;bottom:56px;width:42px;height:54px;font-size:38px}.v6Prev{left:12px}.v6Next{right:12px}#dslV6Lightbox figure img{max-height:72vh}.v6Clickable:after{font-size:8px}}';document.head.appendChild(s)}
function bindLb(){var b=lightbox();q('.v6Close',b).onclick=closeLb;q('.v6Prev',b).onclick=function(){if(lbRoot)showLb(lbRoot,lbIndex-1)};q('.v6Next',b).onclick=function(){if(lbRoot)showLb(lbRoot,lbIndex+1)};b.onclick=function(e){if(e.target===b)closeLb()};document.addEventListener('keydown',function(e){if(!b.classList.contains('on'))return;if(e.key==='Escape')closeLb();if(e.key==='ArrowLeft'&&lbRoot)showLb(lbRoot,lbIndex-1);if(e.key==='ArrowRight'&&lbRoot)showLb(lbRoot,lbIndex+1)});b.addEventListener('touchstart',function(e){touchX=e.changedTouches[0].clientX},{passive:true});b.addEventListener('touchend',function(e){var d=e.changedTouches[0].clientX-touchX;if(Math.abs(d)>45&&lbRoot)showLb(lbRoot,lbIndex+(d<0?1:-1))},{passive:true})}
function loadV4(){if(q('script[data-dsl-v4]'))return;var s=document.createElement('script');s.defer=true;s.dataset.dslV4='1';s.src=BASE+'js/drivespeclab-v4.js';document.head.appendChild(s)}
brand=brandFromPath();if(!brand)return;css();bindLb();document.addEventListener('DriveSpecLabDBReady',function(e){db=e.detail||window.DriveSpecLabDB;mergeOverlay();watch();setTimeout(process,50)});loadJson(BASE+'data/v6/'+slug(brand)+'.json').then(function(x){overlay=x;mergeOverlay();process()});loadV4();
})();
